### PR TITLE
newUpdate

### PR DESCRIPTION
**Pull request by abideen305**
newUpdate

### CODE REVIEW

**Comment by abideen305** [comment]
Please check for me

**Comment by Generalsoi** [comment]
Check the slack channel for the right format. You are almost correct

**Comment by ajdelgados** [comment]
Pls, modify your code with following instructions https://hngi7.slack.com/archives/C014MD11S7P/p1591189194050900

**Comment by ajdelgados** [comment]
Pls, resolve conflicts or close PR

**Comment by abideen305** [comment]
I have disregard all pull. It's the last one I am using

**Comment by abideen305** [comment]
The correct pull is #456. I hope it will pass this time.

**Pull request closed without merging**
