### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by drBamz**
Just added my js file. Email: bamz4all@gmail.com

### CODE REVIEW

**Comment by Generalsoi** [comment]
Check out the format for adding email from the slack channel.

**Comment by ajdelgados** [comment]
Why do you have 2 files?

**Comment by drBamz** [comment]
The first file was an error. I uploaded the whole zip file back.

Adibe Bamidele

**Comment by drBamz** [comment]
Thank you sir. But I can't find it in the result page.

Adibe Bamidele

**Pull request merged**
