### PR TITLE
committed miracle.js file

### PR DESCRIPTION
**Pull request by MirakleDdev**
miracle.js file

### CODE REVIEW

**Comment by ajdelgados** [comment]
I see a extra console.log, line 9

**Comment by MirakleDdev** [comment]
Is the line 9 wrong to be there

**Comment by ajdelgados** [comment]
Yes, because print extra information
You need to delete

**Comment by MirakleDdev** [comment]
So I'll edit on my forked repo and then pull request again right?

**Comment by ajdelgados** [comment]
Yes!

**Comment by MirakleDdev** [comment]
Hey.. i have changed it and then made a pull request. But it didn't ask me
to commit it.

**Pull request merged**
