### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by oladolapo**

### CODE REVIEW

**Comment by ajdelgados** [comment]
Pls, modify your code with following instructions https://hngi7.slack.com/archives/C014MD11S7P/p1591189194050900

**Comment by oladolapo** [comment]
made new changes

**Comment by oladolapo** [comment]
> Pls, modify your code with following instructions https://hngi7.slack.com/archives/C014MD11S7P/p1591189194050900

done.. please i can't seem to find my script in result page

**Comment by oladolapo** [comment]
new out put added

**Pull request merged**
