### PR TITLE
fixed the JavaScript name

### PR DESCRIPTION
**Pull request by Onyedikachi123**

### CODE REVIEW

**Comment by sosualfred** [comment]
Excellent but your pull request did not pass the auto merge feature.

**Comment by Onyedikachi123** [comment]
What do advice I do

**Comment by sosualfred** [comment]
I advise you delete your current forked repo, fork this repo all over again, create a new file in the scripts folder make your changes and commit. Then, make a pull request.

**Comment by Onyedikachi123** [comment]
Hello done it,

**Pull request closed without merging**
