### PR TITLE
Update my php script for HNGI stage 1 Task

### PR DESCRIPTION
**Pull request by Merlin4190**
Add my php script for HNGI stage 1 Task. Please, kindly update me if the script run smoothly or successfully. Thanks for the hard work.

### CODE REVIEW

**Comment by ajdelgados** [comment]
I don't see your email
Pls, modify your code with following instructions https://hngi7.slack.com/archives/C014MD11S7P/p1591189194050900

**Comment by Merlin4190** [comment]
i have updated it. Thanks

**Comment by Merlin4190** [comment]
Please, still awaiting a confirmation. Thanks

**Comment by Merlin4190** [comment]
Re-updated again removing json encode function

**Pull request merged**
