### PR TITLE
this is my task

### PR DESCRIPTION
**Pull request by Balkiss-hue**
Please merge this

### CODE REVIEW

**Comment by ajdelgados** [comment]
I don't see your email in console.log

**Comment by Balkiss-hue** [comment]
Ohh
Sorry about that, it would be rectified now!

**Comment by Balkiss-hue** [comment]
Hello,
Please I'm not able to merge the file. I push the edited one but can't see
it in the repository.

I'd appreciate your prompt response please.

**Comment by sosualfred** [comment]
Please create new repo and send Pull Request, there are conflicts

**Pull request closed without merging**
