### PR TITLE
First initial commit to Team Superman

### PR DESCRIPTION
**Pull request by uchedotphp**
Added email

### CODE REVIEW

**Comment by DreyWesson** [comment]
You hard coded your details...please check

**Comment by ajdelgados** [comment]
Pls, modify your code with following instructions https://hngi7.slack.com/archives/C014MD11S7P/p1591189194050900

**Comment by sosualfred** [comment]
Please create new repo and send Pull Request, there are conflicts

**Comment by uchedotphp** [comment]
Already made the changes and created a new PR

**Pull request closed without merging**
