### PR TITLE
Create MillieKiruri_script.js

### PR DESCRIPTION
**Pull request by MissKiruri**
my script.js

### CODE REVIEW

**Comment by DreyWesson** [comment]
add your email pls

**Comment by MissKiruri** [comment]
How do I do that please... I'm stuck...

**Comment by ajdelgados** [comment]
Pls, modify your code with following instructions https://hngi7.slack.com/archives/C014MD11S7P/p1591189194050900

**Comment by MissKiruri** [comment]
I have made the necessary changes. Thank you very much for your help.

**Pull request merged**
