### PR TITLE
Update astonGemmy.js

### PR DESCRIPTION
**Pull request by AstonGemmy**
I hope it's okay now.

### CODE REVIEW

**Comment by chydube** [comment]
Kindly follow the right script format.... your email is not included in you script.

**Comment by AstonGemmy** [comment]
> Kindly follow the right script format.... your email is not included in your script.

Email is now added. Is that okay? If not please specify everything that's lacking so I could fix it at once and be done with this. I'm using my phone for this whole thing and it's really uncomfortable for me. Thanks.

**Comment by chydube** [comment]
it will scale wait for merge

**Comment by AstonGemmy** [comment]
> it will scale wait for merge

Alright.

**Pull request merged**
