### PR TITLE
Hansonnnadi-HND-00018 script

### PR DESCRIPTION
**Pull request by Hansonnnadi**
Hanson requesting to merge hanson.js

### CODE REVIEW

**Comment by Hansonnnadi** [comment]
Please I don't where the other files are coming from I am only trying to merge mine - hanson.js

**Comment by Temitope25** [comment]
Not yet deployed. Merged

**Comment by Temitope25** [comment]
Not meged. Conflict.

**Comment by Hansonnnadi** [comment]
Is the conflict for hanson.js?

**Comment by Hansonnnadi** [comment]
Please view "updated submission" - only one file this time around - hanson1.js

**Pull request closed without merging**
