### PR TITLE
please merge my request since yesterday

### PR DESCRIPTION
**Pull request by vigosofts**

### CODE REVIEW

**Comment by Generalsoi** [comment]
We cannot merge your pull request because it's conflicting with index.php

**Comment by Generalsoi** [comment]
Do a new fork and please do not touch the index.php file, just add your script to the scripts folder

**Comment by vigosofts** [comment]
Thanks for the feedback.... i never knew about this commenting feature

**Comment by sosualfred** [comment]
Please create new repo and send Pull Request

**Pull request closed without merging**
